#+TITLE: Gentoo Linux amd64 Handbook: Installing Gentoo
* Introduction

** Welcome

First of all, welcome to Gentoo. You are about to enter the world of choices and performance. Gentoo is all about choices. When installing Gentoo, this is made clear several times -- users can choose how much they want to compile themselves, how to install Gentoo, what system logger to use, etc.

Gentoo is a fast, modern meta-distribution with a clean and flexible design. Gentoo is built around free software and doesn't hide from its users what is beneath the hood. Portage, the package maintenance system which Gentoo uses, is written in Python, meaning the user can easily view and modify the source code. Gentoo's packaging system uses source code (although support for precompiled packages is included too) and configuring Gentoo happens through regular text files. In other words, openness everywhere.

It is very important that everybody understands that choices are what makes Gentoo run. We try not to force users onto anything they don't like. If anyone believes otherwise, please [[https://bugs.gentoo.org/][bugreport]] it.

** How is instruction structured

The Gentoo Installation can be seen as a 10-step procedure, corresponding to the next set of chapters. Every step results in a certain state:

    1. After step 1, the user is in a working environment ready to install Gentoo
    2. After step 2, the Internet connection is ready to install Gentoo
    3. After step 3, the hard disks are initialized to host the Gentoo installation
    4. After step 4, the installation environment is prepared and the user is ready to chroot into the new environment
    5. After step 5, core packages, which are the same on all Gentoo installations, are installed
    6. After step 6, the Linux kernel is installed
    7. After step 7, the user will have configured most of the Gentoo system configuration files
    8. After step 8, the necessary system tools are installed
    9. After step 9, the proper boot loader has been installed and configured
    10. After step 10, the freshly installed Gentoo Linux environment is ready to be explored

Whenever a certain choice is presented, the handbook will try to explain what the pros and cons are. Although the text then continues with a default choice (identified by "Default: " in the title), the other possibilities will be documented as well (marked by "Alternative: " in the title). Do not think that the default is what Gentoo recommends. It is however what Gentoo believes most users will use.

Sometimes an optional step can be followed. Such steps are marked as "Optional: " and are therefore not needed to install Gentoo. However, some optional steps are dependent on a previous decision made. The instructions will inform the reader when this happens, both when the decision is made, and right before the optional step is described.

** What are the options

Gentoo can be installed in many different ways. It can be downloaded and installed from one of Gentoo's Installation CDs, from a distribution already installed, from a non-Gentoo bootable CD (such as Knoppix), from a netbooted environment, from a rescue floppy, etc.

This document covers the installation using a Gentoo Installation CD or, in certain cases, netbooting.

#BEGIN_QUOTE
*Note*

For help on the other installation approaches, including using non-Gentoo CDs, please read our [[https://wiki.gentoo.org/wiki/Installation_alternatives][Alternative Installation Guide]].
#END_QUOTE

We also provide a [[https://wiki.gentoo.org/wiki/Gentoo_installation_tips_and_tricks][Gentoo Installation Tips & Tricks]] document that might be useful to read as well.

** Troubles

if a problem is found in the installation (or in the installation documentation), please visit our [[https://bugs.gentoo.org/][bugtracking system]] and check if the bug is known. If not, please create a [[https://bugs.gentoo.org/][bugreport]] for it so we can take care of it. Do not be afraid of the developers who are assigned to the bugs -- they (generally) don't eat people.

Note though that, although this document is architecture-specific, it might contain references to other architectures as well. This is due to the fact that large parts of the Gentoo Handbook use source code that is common for all architectures (to avoid duplication of efforts and starvation of development resources). We will try to keep this to a minimum to avoid confusion.

If there is some uncertainty whether or not the problem is a user-problem (some error made despite having read the documentation carefully) or a software-problem (some error we made despite having tested the installation/documentation carefully) everybody is welcome to join #gentoo on irc.freenode.net. Of course, everyone is welcome otherwise too as our chat channel covers the broad Gentoo spectrum.

Speaking of which, if there are any additional questions regarding Gentoo, check out our [[https://wiki.gentoo.org/wiki/FAQ][Frequently Asked Questions]], available from the [[https://wiki.gentoo.org/wiki/Main_Page][Gentoo Wiki]]. There are also [[https://forums.gentoo.org/viewforum.php?f=40][FAQs]] on the [[https://forums.gentoo.org/][Gentoo Forums]].

* Hardware requirements

Before we start, we first list what hardware requirements are needed to successfully install Gentoo on a amd64 box.

|           | Minimal CD                           | LiveDVD                                |
| CPU       | Any AMD64 CPU or [[http://en.wikipedia.org/wiki/EMT64#Intel_64][EM64T]] CPU (Core 2 Duo & Quad processors are EM64T)      |
| Memory    | 256 MB                               | 512 MB                                 |
| Diskspace | 2.5 GB (excluding swap space)                                                 |
| Swapspace | At least 256 MB                                                               |

[[https://www.gentoo.org/proj/en/base/amd64/][The Gentoo AMD64 project site]] is a good place to be for more information about Gentoo's AMD64 support.

* Gentoo Linux installation CD

** Minimal installation CD

The Gentoo minimal installation CD is a bootable CD which contains a self-sustained Gentoo environment. It allows the user to boot Linux from the CD. During the boot process the hardware is detected and the appropriate drivers are loaded. The CD is maintained by Gentoo developers and allows anyone to install Gentoo if an active Internet connection is available.

The Minimal Installation CD is called /install-amd64-minimal-<release>.iso/.

** The occasional Gentoo LiveDVD

Occasionally, a special DVD is crafted by the Gentoo Ten project which can be used to install Gentoo. The instructions further down this chapter target the Minimal Installation CD so might be a bit different. However, the LiveDVD (or any other bootable Linux environment) supports getting a root prompt by just invoking =sudo su -= or =sudo -i= on a terminal.

** What are stages then?

A stage3 tarball is an archive containing a minimal Gentoo environment, suitable to continue the Gentoo installation using the instructions in this manual. Previously, the Gentoo Handbook described the installation using one of three stage tarballs. While Gentoo still offers stage1 and stage2 tarballs, the official installation method uses the stage3 tarball. If you are interested in performing a Gentoo installation using a stage1 or stage2 tarball, please read the Gentoo FAQ on [[https://wiki.gentoo.org/wiki/FAQ#How_do_I_Install_Gentoo_Using_a_Stage1_or_Stage2_Tarball.3F][How do I Install Gentoo Using a Stage1 or Stage2 Tarball]]?

Stage3 tarballs can be downloaded from /releases/amd64/autobuilds/ on any of the [[https://www.gentoo.org/downloads/mirrors/][official Gentoo mirrors]] and are not provided by the installation CD.

* Downloading and burning the CD Download the media

** Download the media

The default installation media that Gentoo Linux uses are the minimal installation CDs, which host a bootable, very small Gentoo Linux environment with the right tools to install Gentoo Linux from. The CD images themselves can be downloaded from one of the many mirrors available.

On those mirrors, the minimal installation CDs can be found as follows:

    1. Go to the releases/ directory
    2. Select the right architecture, such as amd64/
    3. Select the autobuilds/ directory
    4. Select the current-iso/ directory

Inside this location, the installation CD file is the file with the .iso suffix. For instance, take a look at the following listing:

#+BEGIN_SRC
CODE Example list of downloadable files at releases/amd64/autobuilds/current-iso/

[DIR] hardened/                                         05-Dec-2014 01:42 -
[   ] install-amd64-minimal-20141204.iso                04-Dec-2014 21:04 208M
[   ] install-amd64-minimal-20141204.iso.CONTENTS       04-Dec-2014 21:04 3.0K
[   ] install-amd64-minimal-20141204.iso.DIGESTS        04-Dec-2014 21:04 740
[TXT] install-amd64-minimal-20141204.iso.DIGESTS.asc    05-Dec-2014 01:42 1.6K
[   ] stage3-amd64-20141204.tar.bz2                     04-Dec-2014 21:04 198M
[   ] stage3-amd64-20141204.tar.bz2.CONTENTS            04-Dec-2014 21:04 4.6M
[   ] stage3-amd64-20141204.tar.bz2.DIGESTS             04-Dec-2014 21:04 720
[TXT] stage3-amd64-20141204.tar.bz2.DIGESTS.asc         05-Dec-2014 01:42 1.5K
#+END_SRC

In the above example, the install-amd64-minimal-20141204.iso file is the minimal installation CD itself. But as can be seen, other related files exist as well:

    - A .CONTENTS file which is a text file listing all files available on the installation CD. This file can be useful to verify if particular firmware or drivers are available on the installation CD before downloading it.
    - A .DIGESTS file which contains the hash of the ISO file itself, in various hashing formats/algorithms. This file can be used to verify if the downloaded ISO file is corrupt or not.
    - A .DIGESTS.asc file which not only contains the hash of the ISO file (like the .DIGESTS file), but also a cryptographic signature of that file. This can be used to both verify if the downloaded ISO file is corrupt or not, as well as verify that the download is indeed provided by the Gentoo Release Engineering team and has not been tampered with.

Ignore the other files available at this location for now - those will come back when the installation has proceeded further. Download the .ISO file and, if verification of the download is wanted, download the .DIGESTS.asc file for the ISO file as well. The .CONTENTS file does not need to be downloaded as the installation instructions will not refer to this file anymore, and the .DIGESTS file should contain the same information as the .DIGESTS.asc file, except that the latter also contains a signature on top of it.

** Verifying the downloaded files

#+BEGIN_QUOTE
*Note*

This is an optional step and not necessary to install Gentoo Linux. However, it is recommended as it ensures that the downloaded file is not corrupt and has indeed been provided by the Gentoo Infrastructure team.
#+END_QUOTE

Through the .DIGESTS and .DIGESTS.asc files, the validity of the ISO file can be confirmed using the right set of tools. This verification is usually done in two steps:

  1. First, the cryptographic signature is validated to make sure that the installation file is provided by the Gentoo Release Engineering team
  2. If the cryptographic signature validates, then the checksum is verified to make sure that the downloaded file itself is not corrupted

** Microsoft Windows based verification

On a Microsoft Windows system, chances are low that the right set of tools to verify checksums and cryptographic signatures are in place.

To first verify the cryptographic signature, tools such as [[http://www.gpg4win.org/][GPG4Win]] can be used. After installation, the public keys of the Gentoo Release Engineering team need to be imported. The list of keys is available on the [[https://www.gentoo.org/downloads/signatures/][signatures page]]. Once imported, the user can then verify the signature of the .DIGESTS.asc file.

#+BEGIN_QUOTE
*Important*

This does not verify that the .DIGESTS file is correct, only that the .DIGESTS.asc file is. That also implies that the checksum should be verified against the values in the .DIGESTS.asc file, which is why the instructions above only refer to downloading the .DIGESTS.asc file.
#+END_QUOTE

The checksum itself can be verified using the [[http://www.sinf.gr/en/hashcalc.html][Hashcalc application]], although many others exist as well. Most of the time, these tools will show the user the calculated checksum, and the user is requested to verify this checksum with the value that is inside the .DIGESTS.asc file.

** Linux based verification

On a Linux system, the most common method for verifying the cryptographic signature is to use the [[http://packages.gentoo.org/package/app-crypt/gnupg][app-crypt/gnupg]] software. With this package installed, the following commands can be used to verify the cryptographic signature of the .DIGESTS.asc file.

First, download the right set of keys as made available on the signatures page:

#+BEGIN_SRC
user $ gpg --recv-keys 0xBB572E0E2D182910

gpg: requesting key 0xBB572E0E2D182910 from hkp server pool.sks-keyservers.net
gpg: key 0xBB572E0E2D182910: "Gentoo Linux Release Engineering (Automated Weekly Release Key) <releng@gentoo.org>" 1 new signature
gpg: 3 marginal(s) needed, 1 complete(s) needed, classic trust model
gpg: depth: 0  valid:   3  signed:  20  trust: 0-, 0q, 0n, 0m, 0f, 3u
gpg: depth: 1  valid:  20  signed:  12  trust: 9-, 0q, 0n, 9m, 2f, 0u
gpg: next trustdb check due at 2018-09-15
gpg: Total number processed: 1
gpg:         new signatures: 1
#+END_SRC

Next verify the cryptographic signature of the .DIGESTS.asc file:

#+BEGIN_SRC
user $ gpg --verify install-amd64-minimal-20141204.iso.DIGESTS.asc

gpg: Signature made Fri 05 Dec 2014 02:42:44 AM CET
gpg:                using RSA key 0xBB572E0E2D182910
gpg: Good signature from "Gentoo Linux Release Engineering (Automated Weekly Release Key) <releng@gentoo.org>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 13EB BDBE DE7A 1277 5DFD  B1BA BB57 2E0E 2D18 2910
#+END_SRC

To be absolutely certain that everything is valid, verify the fingerprint shown with the fingerprint on the Gentoo signatures page.

With the cryptographic signature validated, next verify the checksum to make sure the downloaded ISO file is not corrupted. The .DIGESTS.asc file contains multiple hashing algorithms, so one of the methods to validate the right one is to first look at the checksum registered in the .DIGESTS.asc file. For instance, to get the SHA512 checksum:

#+BEGIN_SRC
user $ grep -A 1 -i sha512 install-amd64-minimal-20141204.iso.DIGESTS.asc

# SHA512 HASH
364d32c4f8420605f8a9fa3a0fc55864d5b0d1af11aa62b7a4d4699a427e5144b2d918225dfb7c5dec8d3f0fe2cddb7cc306da6f0cef4f01abec33eec74f3024  install-amd64-minimal-20141204.iso
--
# SHA512 HASH
0719a8954dc7432750de2e3076c8b843a2c79f5e60defe43fcca8c32ab26681dfb9898b102e211174a895ff4c8c41ddd9e9a00ad6434d36c68d74bd02f19b57f  install-amd64-minimal-20141204.iso.CONTENTS
#+END_SRC

In the above output, two SHA512 checksums are shown - one for the install-amd64-minimal-20141204.iso file and one for its accompanying .CONTENTS file. Only the first checksum is of interest, as it needs to be compared with the calculated SHA512 checksum which can be generated as follows:

#+BEGIN_SRC
user $ sha512sum install-amd64-minimal-20141204.iso

364d32c4f8420605f8a9fa3a0fc55864d5b0d1af11aa62b7a4d4699a427e5144b2d918225dfb7c5dec8d3f0fe2cddb7cc306da6f0cef4f01abec33eec74f3024  install-amd64-minimal-20141204.iso
#+END_SRC

As both checksums match, the file is not corrupted and the installation can continue.

** Burning

Of course, with just an ISO file downloaded, the Gentoo Linux installation cannot be started. The ISO file needs to be burned on a CD to boot from, and in such a way that its content is burned on the CD, not just the file itself. Below a few common methods are described - a more elaborate set of instructions can be found in [[https://wiki.gentoo.org/wiki/FAQ#How_do_I_burn_an_ISO_file.3F][Our FAQ on burning an ISO file]].

*** Burning with Microsoft Windows

On Microsoft Windows, a number of tools exist that support burning ISOs on CDs.

    - With EasyCD Creator, select File, Record CD from CD image. Then change the Files of type to ISO image file. Then locate the ISO file and click Open. After clicking on Start recording the ISO image will be burned correctly onto the CD-R.
    - With Nero Burning ROM, cancel the wizard which automatically pops up and select Burn Image from the File menu. Select the image to burn and click Open. Now hit the Burn button and watch the brand new CD being burnt.

Burning with Linux

On Linux, the ISO file can be burned on a CD using the =cdrecord= command, part of the [[http://packages.gentoo.org/package/app-cdr/cdrtools][app-cdr/cdrtools]] package.

For instance, to burn the ISO file on the CD in the /dev/sr0 device (this is the first CD device on the system - substitute with the right device file if necessary):

#+BEGIN_SRC
user $ cdrecord dev=/dev/sr0 install--minimal-20141204.iso
#+END_SRC

Users that prefer a graphical user interface can use K3B, part of the [[http://packages.gentoo.org/package/app-cdr/k3b][app-cdr/k3b]] package. In K3B, go to Tools and use Burn CD Image. Then follow the instructions provided by K3B.

* Booting the CD

** Booting the installation CD

Once the installation CD is burned, it is time to boot it. Remove all CDs from the CD drives, reboot the system and enter the BIOS or UEFI. This is usually done by hitting =DEL=, =F1= or =ESC=, which is highly depending on the system and motherboard used. Inside the BIOS or UEFI menu, change the boot order so that the CD-ROM is tried before the hard disk. Without this change, the system will just reboot from the hard disk, ignoring the CD-ROM.

#+BEGIN_QUOTE
*Important*

When installing Gentoo with the purpose of using the UEFI interface instead of BIOS, it is recommended to boot with UEFI immediately. If not, then it might be necessary to create a bootable UEFI USB stick (or other medium) once before finalizing the Gentoo Linux installation.
#+END_QUOTE

Now place the installation CD in the CD-ROM drive and reboot. A boot prompt should be shown. At this screen, =Enter= will begin the boot process with the default boot options. To boot the installation CD with custom boot options, specify a kernel followed by boot options and then hit =Enter=.

At the boot prompt, users get the option of displaying the available kernels (=F1=) and boot options (=F2=). If no choice is made within 15 seconds (either displaying information or using a kernel) then the installation CD will fall back to booting from disk. This allows installations to reboot and try out their installed environment without the need to remove the CD from the tray (something well appreciated for remote installations).

We mentioned specifying a kernel. On the installation CD, several
kernels are provided. The default one is called gentoo. Other kernels
are for specific hardware needs and the /-nofb/ variants disable
framebuffer support.

The next table gives a short overview of the available kernels.

| Kernel      | Description                                                                     |
|-------------+---------------------------------------------------------------------------------|
| gentoo      | Default kernel with support for K8 CPUs (including NUMA support) and EM64T CPUs |
| gentoo-nofb | Same as gentoo but without framebuffer support                                  |
| memtest86   | Test the local RAM for errors                                                   |

Alongside the kernel, boot options help in tuning the boot process further.

|             | Hardware options                                                                                                                                                                                                                                                    |
|-------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| acpi=on     | This loads support for ACPI and also causes the acpid daemon to be started by the CD on boot. This is only needed if the system requires ACPI to function properly. This is not required for Hyperthreading support.                                                |
| acpi=off    | Completely disables ACPI. This is useful on some older systems and is also a requirement for using APM. This will disable any Hyperthreading support of your processor.                                                                                             |
| console=X   | This sets up serial console access for the CD. The first option is the device, usually ttyS0 on x86, followed by any connection options, which are comma separated. The default options are 9600,8,n,1.                                                             |
| dmraid=X    | This allows for passing options to the device-mapper RAID subsystem. Options should be encapsulated in quotes.                                                                                                                                                      |
| doapm       | This loads APM driver support. This also requires that =acpi=off=.                                                                                                                                                                                                  |
| dopcmcia    | This loads support for PCMCIA and Cardbus hardware and also causes the pcmcia cardmgr to be started by the CD on boot. This is only required when booting from PCMCIA/Cardbus devices.                                                                              |
| doscsi      | This loads support for most SCSI controllers. This is also a requirement for booting most USB devices, as they use the SCSI subsystem of the kernel.                                                                                                                |
| sda=stroke  | This allows the user to partition the whole hard disk even when the BIOS is unable to handle large disks. This option is only used on machines with an older BIOS. Replace sda with the device that requires this option.                                           |
| ide=nodma   | This forces the disabling of DMA in the kernel and is required by some IDE chipsets and also by some CDROM drives. If the system is having trouble reading from the IDE CDROM, try this option. This also disables the default hdparm settings from being executed. |
| noapic      | This disables the Advanced Programmable Interrupt Controller that is present on newer motherboards. It has been known to cause some problems on older hardware.                                                                                                     |
| nodetect    | This disables all of the autodetection done by the CD, including device autodetection and DHCP probing. This is useful for doing debugging of a failing CD or driver.                                                                                               |
| nodhcp      | This disables DHCP probing on detected network cards. This is useful on networks with only static addresses.                                                                                                                                                        |
| nodmraid    | Disables support for device-mapper RAID, such as that used for on-board IDE/SATA RAID controllers.                                                                                                                                                                  |
| nofirewire  | This disables the loading of Firewire modules. This should only be necessary if your Firewire hardware is causing a problem with booting the CD.                                                                                                                    |
| nogpm       | This disables gpm console mouse support.                                                                                                                                                                                                                            |
| nohotplug   | This disables the loading of the hotplug and coldplug init scripts at boot. This is useful for doing debugging of a failing CD or driver.                                                                                                                           |
| nokeymap    | This disables the keymap selection used to select non-US keyboard layouts.                                                                                                                                                                                          |
| nolapic     | This disables the local APIC on Uniprocessor kernels.                                                                                                                                                                                                               |
| nosata      | This disables the loading of Serial ATA modules. This is used if the system is having problems with the SATA subsystem.                                                                                                                                             |
| nosmp       | This disables SMP, or Symmetric Multiprocessing, on SMP-enabled kernels. This is useful for debugging SMP-related issues with certain drivers and motherboards.                                                                                                     |
| nosound     | This disables sound support and volume setting. This is useful for systems where sound support causes problems.                                                                                                                                                     |
| nousb       | This disables the autoloading of USB modules. This is useful for debugging USB issues.                                                                                                                                                                              |
| slowusb     | This adds some extra pauses into the boot process for slow USB CDROMs, like in the IBM BladeCenter.                                                                                                                                                                 |
|-------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
|             | Logical volume/device management                                                                                                                                                                                                                                    |
|-------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| dolvm       | This enables support for Linux's Logical Volume Management.                                                                                                                                                                                                         |
|-------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
|             | Other options                                                                                                                                                                                                                                                       |
|-------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| debug       | Enables debugging code. This might get messy, as it displays a lot of data to the screen.                                                                                                                                                                           |
| docache     | This caches the entire runtime portion of the CD into RAM, which allows the user to umount /mnt/cdrom and mount another CDROM. This option requires that there is at least twice as much available RAM as the size of the CD.                                       |
| doload=X    | This causes the initial ramdisk to load any module listed, as well as dependencies. Replace X with the module name. Multiple modules can be specified by a comma-separated list.                                                                                    |
| dosshd      | Starts sshd on boot, which is useful for unattended installs.                                                                                                                                                                                                       |
| passwd=foo  | Sets whatever follows the equals as the root password, which is required for dosshd since the root password is by default scrambled.                                                                                                                                |
| noload=X    | This causes the initial ramdisk to skip the loading of a specific module that may be causing a problem. Syntax matches that of doload.                                                                                                                              |
| nonfs       | Disables the starting of portmap/nfsmount on boot.                                                                                                                                                                                                                  |
| nox         | This causes an X-enabled LiveCD to not automatically start X, but rather, to drop to the command line instead.                                                                                                                                                      |
| scandelay   | This causes the CD to pause for 10 seconds during certain portions the boot process to allow for devices that are slow to initialize to be ready for use.                                                                                                           |
| scandelay=X | This allows the user to specify a given delay, in seconds, to be added to certain portions of the boot process to allow for devices that are slow to initialize to be ready for use. Replace X with the number of seconds to pause.                                 |

#+BEGIN_QUOTE
*Note*

The CD will check for =no*= options before =do*= options, so that options can be overriden in the exact order specified.
#+END_QUOTE

Now boot the CD, select a kernel (if the default =gentoo= kernel does
not suffice) and boot options. As an example, we boot the =gentoo=
kernel, with =dopcmcia= as a kernel parameter:

#+BEGIN_SRC
boot: gentoo dopcmcia
#+END_SRC

Next the user will be greeted with a boot screen and progress bar. If the installation is done on a system with a non-US keyboard, make sure to immediately press =Alt= + =F1= to switch to verbose mode and follow the prompt. If no selection is made in 10 seconds the default (US keyboard) will be accepted and the boot process will continue. Once the boot process completes, the user is automatically logged in to the "Live" Gentoo Linux environment as the root user, the super user. A root prompt is displayed on the current console, and one can switch to other consoles by pressing =Alt= + =F2=, =Alt= + =F3= and =Alt= + =F4=. Get back to the one started on by pressing =Alt= + =F1=.

** Extra hardware configuration

When the Installation CD boots, it tries to detect all the hardware devices and loads the appropriate kernel modules to support the hardware. In the vast majority of cases, it does a very good job. However, in some cases it may not auto-load the kernel modules needed by the system. If the PCI auto-detection missed some of the system's hardware, the appropriate kernel modules have to be loaded manually.

In the next example the 8139too module (which supports certain kinds of network interfaces) is loaded:

#+BEGIN_SRC
root # modprobe 8139too
#+END_SRC

** Optional: User accounts

If other people need access to the installation environment, or there is need to run commands as a non-root user on the installation CD (such as to chat using =irssi= without root privileges for security reasons), then an additional user account needs to be created and the root password set to a strong password.

To change the root password, use the passwd utility:

#+BEGIN_SRC
root # passwd
New password: (Enter your new password)
Re-enter password: (Re-enter your password)
#+END_SRC

To create a user account, first enter their credentials, followed by
the account's password. The =useradd= and =passwd= commands are used for
these tasks.

In the next example, a user called /john/ is created:

#+BEGIN_SRC
root # useradd -m -G users john
root # passwd john
New password: (Enter john's password)
Re-enter password: (Re-enter john's password)
#+END_SRC

To switch from the (current) root user to the newly created user account, use the su command:

#+BEGIN_SRC
root # su - john
#+END_SRC

** Optional: Viewing documentation while installing

To view the Gentoo handbook during the installation, first create a user account as described above. Then press =Alt= + =F2= to go to a new terminal.

During the installation, the =links= command can be used to browse the Gentoo handbook - of course only from the moment that the Internet connection is working.

#+BEGIN_SRC
user $ links https://wiki.gentoo.org/wiki/Handbook:AMD64
#+END_SRC

To go back to the original terminal, press =Alt= + =F1=.

** Optional: Starting the SSH daemon

To allow other users to access the system during the installation
(perhaps to support during an installation, or even do it remotely), a
user account needs to be created (as was documented earlier on) and
the SSH daemon needs to be started.

To fire up the SSH daemon, execute the following command:

#+BEGIN_SRC
root # /etc/init.d/sshd start
#+END_SRC

#+BEGIN_QUOTE
*Note*

If users log on to the system, they will get a message that the host key for this system needs to be confirmed (through what is called a fingerprint). This is to be expected as it is the first time people log on to the system. However, later when the system is set up and someone logs on to the newly created system, the SSH client will warn that the host key has been changed. This is because the user now log on to - for SSH - a different server (namely the freshly installed Gentoo system rather than the live environment that the installation is currently using). Follow the instructions given on the screen then to replace the host key on the client system.
#+END_QUOTE

To be able to use sshd, the network needs to function
properly. Continue with the chapter on [[https://wiki.gentoo.org/wiki/Handbook:AMD64/Installation/Networking][Configuring the network]].
