#+TITLE: Gentoo Linux amd64 手册: 安装Gentoo
* 序言
** 欢迎
#+BEGIN_QUOTE
First of all, welcome to Gentoo. You are about to enter the world of choices and performance. Gentoo is all about choices. When installing Gentoo, this is made clear several times -- users can choose how much they want to compile themselves, how to install Gentoo, what system logger to use, etc.

Gentoo is a fast, modern meta-distribution with a clean and flexible design. Gentoo is built around free software and doesn't hide from its users what is beneath the hood. Portage, the package maintenance system which Gentoo uses, is written in Python, meaning the user can easily view and modify the source code. Gentoo's packaging system uses source code (although support for precompiled packages is included too) and configuring Gentoo happens through regular text files. In other words, openness everywhere.

It is very important that everybody understands that choices are what makes Gentoo run. We try not to force users onto anything they don't like. If anyone believes otherwise, please bugreport it.
#+END_QUOTE

首先，欢迎来到Gentoo。您将进入选择和性能的世界。Gentoo处处都是选择。当安装Gentoo时，这点你会感受到好几次，用户可以选择编译多少软件，怎么安装，系统使用什么系统日志程序等，等等。

Gentoo是一个快速而先进的元发行版本，它有着简洁和灵活的设计理念。Gentoo是由自由软件编译而成，它不向用户隐藏任何东西。Gentoo使用Portage进行软件包管理，它用Python编写而成，用户可以轻松的查看和修改源代码。Gentoo软件包管理系统使用源代码（虽然也支持预编译软件包）进行管理，配置文件使用普通的文本文件。也就是说，处处都是开放的。

让用户明白怎么选择可以运行Gentoo是非常重要的。我们不会强迫用户做他们不喜欢的事情，如果你觉得我有的话，请[[https://bugs.gentoo.org/][告诉]]我们。

** 安装的结构
#+BEGIN_QUOTE
The Gentoo Installation can be seen as a 10-step procedure, corresponding to the next set of chapters. Every step results in a certain state:

    1. After step 1, the user is in a working environment ready to install Gentoo
    2. After step 2, the Internet connection is ready to install Gentoo
    3. After step 3, the hard disks are initialized to host the Gentoo installation
    4. After step 4, the installation environment is prepared and the user is ready to chroot into the new environment
    5. After step 5, core packages, which are the same on all Gentoo installations, are installed
    6. After step 6, the Linux kernel is installed
    7. After step 7, the user will have configured most of the Gentoo system configuration files
    8. After step 8, the necessary system tools are installed
    9. After step 9, the proper boot loader has been installed and configured
    10. After step 10, the freshly installed Gentoo Linux environment is ready to be explored

Whenever a certain choice is presented, the handbook will try to explain what the pros and cons are. Although the text then continues with a default choice (identified by "Default: " in the title), the other possibilities will be documented as well (marked by "Alternative: " in the title). Do not think that the default is what Gentoo recommends. It is however what Gentoo believes most users will use.

Sometimes an optional step can be followed. Such steps are marked as "Optional: " and are therefore not needed to install Gentoo. However, some optional steps are dependent on a previous decision made. The instructions will inform the reader when this happens, both when the decision is made, and right before the optional step is described.
#+END_QUOTE
Gentoo的安装可以视为10个步骤，依照下面的步骤，可以达到相应的状态。

  1. 第1步后，用户处在一个准备安装Gentoo的环境中。
  2. 第2步后，已经准备好用于安装Gentoo的网络环境。
  3. 第3步后，硬盘初始化完毕，可以用于安装Gentoo。
  4. 第4步后，系统环境就绪，用户准备chroot新的环境中。
  5. 第5步后，所有Gentoo都要安装的核心软件包已经安装完毕。
  6. 第6步后，Linux内核安装完毕。
  7. 第7步后，用户已经配置好了大部分Gentoo配置文件。
  8. 第8步后，已经安装好必要的软件。
  9. 第9步后，已经安装并配置好bootloader。
  10. 第10步后，Gentoo环境安装成功，已经可以开始使用了。

当做出一个特定的选择时，手册会解释利与弊。虽然有一个默认的选择用于继续（在标题中用“默认：”标识），同时也会提供其它的可能（在标题中用“选择：”标识），不要认为默认是Gentoo推荐的设置，其实只是Gentoo认为大多数用户会选择它。

有一些并不是安装Gentoo所必须的可选的步骤，这些步骤用“选项：”标识。有一些选项依赖于之前的操作，不用担心，在做出选择时和可选步骤前，我们都会有相应的提示。
